In [1]:
dict={}
n = int(input("Enter the number of books needed: "))
for i in range(n):
    book_name = input("Enter the book name: ")
    book_id = int(input("Enter the book id: "))
    dict[book_id] = book_name

print(dict)

a = int(input("Enter the id to be searched: "))
print("The name of the book for the id",a,"is: ",dict[a])

Enter the number of books needed:  2
Enter the book name:  rich dad
Enter the book id:  102
Enter the book name:  atomic
Enter the book id:  103


{102: 'rich dad', 103: 'atomic'}


Enter the id to be searched:  102


The name of the book for the id 102 is:  rich dad


In [8]:
d1 = {102: 'rich dad', 103: 'atomic'}
type(d1)

dict

In [2]:
list=[]
num = int(input("Enter the number of strings needed: "))
ct = 0
for i in range(num):
    s=input("Enter the string: ")
    list.append(s)
print()
print(list)
print()
for j in list:
    if len(j) >= 2 and j[0]==j[-1]:
        ct+=1
print("The number of strings where the string length is 2 or more and the first and last character are: ",ct)

Enter the number of strings needed:  3
Enter the string:  a2b
Enter the string:  112
Enter the string:  bb



['a2b', '112', 'bb']

The number of strings where the string length is 2 or more and the first and last character are:  1


In [9]:
d1={'Smith', 'McArthur', 'Wilson', 'Johansson'}
d2 = set()
num = int(input("Enter the number of data needed: "))
for i in range(num) :
    data = input("Enter the data: ")
    d2.add(data)
print(d2)

# union 
print("Union :",  d1| d2) 
print()
# intersection 
print("Intersection :", d1 & d2) 
print()  
# difference 
print("Difference :", d1 - d2) 

Enter the number of data needed:  3
Enter the data:  e
Enter the data:  y
Enter the data:  u


{'u', 'e', 'y'}
Union : {'u', 'McArthur', 'Wilson', 'Smith', 'e', 'Johansson', 'y'}

Intersection : set()

Difference : {'Johansson', 'McArthur', 'Wilson', 'Smith'}


In [4]:
t = ()
n = int(input("Enter the number of elements needed: "))
for i in range(n):
    data = int(input("Enter the data: "))  
    t = t + (data,)
sum_of_elements = sum(t)
print("The sum of the tuple elements is:", sum_of_elements)


Enter the number of elements needed:  3
Enter the data:  10
Enter the data:  20
Enter the data:  30


The sum of the tuple elements is: 60


In [6]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

addition_result = matrix1 + matrix2

division_result = matrix1 / matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Addition Result:")
print(addition_result)

print("\nMatrix Division Result:")
print(division_result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Matrix Addition Result:
[[ 8 10 12]
 [14 16 18]]

Matrix Division Result:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
